server.port: ${PORT:8080}
logging.level.org.atmosphere: warn

spring:
  mustache.check-template-location: false
  # Workaround for https://github.com/vaadin/hilla/issues/842
  devtools.restart.additional-exclude: dev/hilla/openapi.json

# Launch the default browser when starting the application in development mode
vaadin.launch-browser: true

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
spring.jpa.defer-datasource-initialization: true

spring.ai.openai:
  api-key: ${OPENAI_API_KEY}
  embedding.transformer.enabled: false
  chat:
    options:
      # model: gpt-3.5-turbo
      model: gpt-4-turbo-preview
      functions: getBookingDetails,changeBooking,cancelBooking